{
 "title": "Local Dashboard",
 "description": "Intended for use when running the system locally via docker.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "docker_machines",
    "label": "docker_machines",
    "query": {
     "query": "label_values(dockerstats_cpu_usage_ratio,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU% (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dockerstats_cpu_usage_ratio{name=~\"$docker_machines\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU% (Custom)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_container_cpu_time_pct{node=~\"$docker_machines\", mode=\"total\"}",
     "legendFormat": "{{node}} {{mode}}"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"proxy\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Transmitted (Docker Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(dockerstats_network_transmitted_bytes{name=~\"$docker_machines\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Received (Docker Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(dockerstats_network_received_bytes{name=~\"$docker_machines\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block IO Written Bytes (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(dockerstats_blockio_written_bytes{name=~\"$docker_machines\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block IO Read Bytes (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "dockerstats_blockio_read_bytes{name=~\"$docker_machines\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Total MB (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_container_memory_usage_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sock Memory MB Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_container_memory_socket_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Slab Memory MB (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_container_memory_slab_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Kernel Memory MB (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "node_container_memory_kernel_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Events: Page Fault (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "node_container_memory_events_total{node=~\"$docker_machines\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage MB (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_bytes{name=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage% (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_ratio{name=~\"$docker_machines\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage MB (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "dockerstats_memory_usage_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Node States",
   "type": "gauge",
   "description": "1 Signifies Instance is up and running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{node}}" }
   ]
  }
 ]
}