{
 "title": "Local Dashboard",
 "description": "Intended for use when running the system locally via docker.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "docker_machines",
    "label": "docker_machines",
    "query": {
     "query": "label_values(dockerstats_cpu_usage_ratio,name)"
    }
   },
   {
    "name": "node_exporter_machine",
    "label": "node_exporter_machine",
    "query": {
     "query": "label_values(node_netstat_Tcp_ActiveOpens,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU% (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dockerstats_cpu_usage_ratio{name=~\"$docker_machines\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU% (Custom)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_container_cpu_time_pct{node=~\"$docker_machines\", mode=\"total\"}",
     "legendFormat": "{{node}} {{mode}}"
    },
    {
     "expr": "dockerstats_cpu_usage_ratio{name=\"proxy\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Transmitted (Docker Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(dockerstats_network_transmitted_bytes{name=~\"$docker_machines\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Bytes Received (Docker Network)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(dockerstats_network_received_bytes{name=~\"$docker_machines\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block IO Written Bytes (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(dockerstats_blockio_written_bytes{name=~\"$docker_machines\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Block IO Read Bytes (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "dockerstats_blockio_read_bytes{name=~\"$docker_machines\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Total MB (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_container_memory_usage_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Sock Memory MB Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_container_memory_socket_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Slab Memory MB (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "node_container_memory_slab_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Kernel Memory MB (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "node_container_memory_kernel_bytes{node=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Events: Page Fault (Cust)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "node_container_memory_events_total{node=~\"$docker_machines\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage MB (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_bytes{name=~\"$docker_machines\"} / 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage% (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "dockerstats_memory_usage_ratio{name=~\"$docker_machines\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage MB (Docker)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    { "expr": "dockerstats_memory_usage_bytes", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "HTTP Reponse Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(node) (rate(http_response_size_bytes_count{node=~\"$docker_machines\"}[$__rate_interval]))",
     "legendFormat": "{{node}} {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Status Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(node, status) (rate(http_requests_total{node=~\"$docker_machines\"}[$__rate_interval]))",
     "legendFormat": "{{node}} {{handler}} {{status}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration Seconds 90th Percentile Rate By Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, node) (rate(http_request_duration_seconds_bucket{node=~\"$docker_machines\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 90th Quant Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, node) (rate(http_request_duration_seconds_bucket{node=~\"$docker_machines\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP Inuse ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_inuse{node=\"target1-node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "TCP Mem ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_mem{node=\"target1-node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "TCP Inuse ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "node_sockstat_sockets_used{node=\"target1-node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "UDP Inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "targets": [
    {
     "expr": "node_sockstat_UDP_inuse{node=\"target1-node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "RAW Inuse",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "node_sockstat_RAW_inuse{node=\"target1-node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "TCP Tw",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "node_sockstat_TCP_tw{node=\"target1-node-exporter\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Net Recv Drop Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "node_network_receive_drop_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Net Recv Errs Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "targets": [
    {
     "expr": "node_network_receive_errs_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Net Transmit Drop Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "node_network_transmit_drop_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Net Transmit Errs Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "node_network_transmit_errs_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Net Transmit Queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "node_network_transmit_queue_length{node=\"target1-node-exporter\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Net Transmit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_packets_total{node=\"target1-node-exporter\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Net CPU Softnet Drop Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "node_softnet_dropped_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net CPU Softnet Sqeeze Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "node_softnet_times_squeezed_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP Retransmissions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_RetransSegs{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net CPU Softnet Sqeeze Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "node_softnet_times_squeezed_total{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP Out Resets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_OutRsts{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP In Errs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_InErrs{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP Listen Overflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "node_netstat_TcpExt_ListenOverflows{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP In Errs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_InErrs{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP Timeouts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "node_netstat_TcpExt_TCPTimeouts{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP Syn Retrans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "node_netstat_TcpExt_TCPSynRetrans{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP Recv Q Drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "targets": [
    {
     "expr": "node_netstat_TcpExt_TCPRcvQDrop{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Net TCP OFO Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 160 },
   "targets": [
    {
     "expr": "node_netstat_TcpExt_TCPOFOQueue{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Available MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 168 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{node=\"target1-node-exporter\"} / 1000000",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Buffers MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 168 },
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{node=\"target1-node-exporter\"} / 1000000",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Slab MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "expr": "node_memory_Slab_bytes{node=\"target1-node-exporter\"} / 1000000",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Stack Reclaimable MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "targets": [
    {
     "expr": "node_memory_SReclaimable_bytes{node=\"target1-node-exporter\"} / 1000000",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Slab UNrelcaimable MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 184 },
   "targets": [
    {
     "expr": "node_memory_SUnreclaim_bytes{node=\"target1-node-exporter\"} / 1000000",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Mem Kernel Stack MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 184 },
   "targets": [
    {
     "expr": "node_memory_KernelStack_bytes{node=\"target1-node-exporter\"} / 1000000",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Conntrack Entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Conntrack Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Conntrack Stat Drop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "targets": [
    {
     "expr": "node_nf_conntrack_stat_drop{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Conntrack Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "targets": [
    {
     "expr": "node_nf_conntrack_entries_limit{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "File Descriptors Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "targets": [
    {
     "expr": "node_filefd_allocated{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "File Descriptor Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 208 },
   "targets": [
    {
     "expr": "node_filefd_maximum{node=\"target1-node-exporter\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU CTX Switches Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 216 },
   "targets": [
    {
     "expr": "rate(node_context_switches_total{node=\"target1-node-exporter\"}[$__rate_interval])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Interrupts Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 216 },
   "targets": [
    {
     "expr": "rate(node_intr_total{node=\"target1-node-exporter\"}[1m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Pressure IO Waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "targets": [
    {
     "expr": "rate(node_pressure_io_waiting_seconds_total{node=\"target1-node-exporter\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure IO Stalled Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 224 },
   "targets": [
    {
     "expr": "rate(node_pressure_io_stalled_seconds_total{node=\"target1-node-exporter\"}[1m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "ICMP In Errs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 232 },
   "targets": [
    {
     "expr": "node_netstat_Icmp_InErrors{node=\"target1-node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICMP In Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InMsgs{node=\"target1-node-exporter\"}[1m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "ICMP In Errs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 240 },
   "targets": [
    {
     "expr": "node_netstat_Icmp_InErrors{node=\"target1-node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ICMP In Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
   "targets": [
    {
     "expr": "rate(node_netstat_Icmp_InMsgs{node=\"target1-node-exporter\"}[1m])",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Node States",
   "type": "gauge",
   "description": "1 Signifies Instance is up and running.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 248 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{node}}" }
   ]
  }
 ]
}