{
 "title": "Beginning Dashboard",
 "time": { "from": "now-3m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "var_machine", "label": "var_machine", "query": { "query": "label_values(up,instance)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_time_pct{instance=\"$var_machine\"}",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_stats_total{instance=\"$var_machine\"}",
     "legendFormat": "{{stat}}"
    }
   ]
  },
  {
   "title": "Memory Slab Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "expr": "node_memory_slab_total{instance=\"$var_machine\"}",
     "legendFormat": "{{type}} {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "CPU Total Time ",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{instance=\"$var_machine\"}",
     "legendFormat": "{{mode}} {{instance}}"
    }
   ]
  },
  {
   "title": "Network Total Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "node_network_total_packets_total{instance=\"$var_machine\"}",
     "legendFormat": "{{type}} {{instance}}"
    }
   ]
  },
  {
   "title": "Swap Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "node_memory_swap_total{instance=\"$var_machine\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network TCP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "node_network_tcp_count{instance=\"$var_machine\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Nginx HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Nginx Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    { "expr": "go_gc_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NGINX Connections waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "nginx_connections_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Nginx Memory Allocated ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}